stages:
  data_collection:
    cmd: python src/data/data_collection.py
    deps:
    - src/data/data_collection.py
    outs:
    - data/raw
  pre_processing:
    cmd: python src/data/data_prep.py
    deps:
    - data/raw
    - src/data/data_prep.py
    outs:
    - data/processed
  model_building:
    cmd: python src/model/model_building.py
    deps:
    - data/processed
    - src/model/model_building.py
    outs:
    - model.pkl
  model_eval:
    cmd: python src/model/model_eval.py
    deps:
    - model.pkl
    - src/model/model_eval.py
    metrics:
    - metrics.json
    outs:
    - reports/run_info.json
  
  model_registration:
    cmd: python src/model/model_reg.py
    deps:
    - reports/run_info.json
    - src/model/model_reg.py


